server:
  port: 80


spring:
  zipkin:
    base-url: http://192.168.6.100:9411/
    sender:
      type: web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**